#include "Version.h"

// Written into $BUILD_DIR/generated by scripts/version.py. Named build_version.h
// rather than version.h because macOS filesystems are case-insensitive by
// default, where "version.h" would resolve back to this module's own Version.h.
#include "build_version.h"

// Isolated in its own translation unit on purpose. The stamp changes on every
// build, so only this file recompiles; putting it in main.cpp would either
// rebuild the world each time or - worse - go stale, which is exactly the trap
// __DATE__/__TIME__ in Log.h used to set.
const char *firmwareVersion()
{
  return FIRMWARE_VERSION;
}
