#pragma once

// The build stamp, e.g. "f67b1e1-dirty 2026-08-21T23:47:03+0200".
//
// Generated by scripts/version.py on every build. The timestamp is the part
// that makes it unique: this project is flashed from a working tree that is
// essentially always dirty, so the git hash alone would be identical across
// every build between commits.
const char *firmwareVersion();
